/*
 * @(#)PropertyValues.java 1.00.12.01.2020
 * Copyright 2020 Statistisches Bundesamt
 * @author Stefan Toengi (Destatis)
 */
package de.destatis.regdb.dateiimport;

/**
 * The Enum PropertyValues.
 */
public enum PropertyValues
{
  MAINJOBID,
  SBID,
  SBLAND,
  STATISTIKID,
  AMT,
  IMPORTFORMAT,
  QUELLREFID,
  ZEICHENSATZ,
  ORIGINALDATEINAME,
  ORDNUNGSFELDLAENGE,
  ORDNUNGSFELDTYP,
  ANZAHLDATENSAETZE,
  DATENSATZOFFSET,
  PASSWORTNICHTAENDERBAR,
  ADRESSENICHTAENDERBAR,
  MELDERZUSAMMENFUEHRBAR,
  NEUEPASSWOERTERGENERIEREN,
  UPDATEFIRMA,
  UPDATEMELDER,
  CREATEFIRMA,
  CREATEMELDER,
  CREATELEEREPARTNER,
  CREATEVORBELEGUNGEN,
  ALLOWLOESCH,
  ZEITPUNKT,
  BZR,
  EINTRAGINFOSCHREIBEN,
  MELDERSPERRE,
  LOESCHERMITTLUNGSLIMIT,
  LOESCHERMITTLUNGSOFFSET,
  ADRESSENIMBESTAND,
  LASTID,
  DATEIUPLOAD,
  MAILVERSAND,
  LOESCHADRESSEN,
  DATEINURPRUEFEN,
  AENDADRESSEN,
  SBKENNUNG,
  SBPASSWORT
}
